# Generated by Django 5.1.1 on 2024-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=11)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
